### ISSUE TITLE
When there is an onDelete, onUpdate and others drizzle doesn't generate the equivalent

### ISSUE THREAD

**Issue by Danieljs-codes** [drizzle-team/drizzle-prisma-generator#5]
When there is an onDelete, onUpdate and others drizzle doesn't generate the equivalent in the drizzle schema I could manually edit the drizzle schema but with every change it gets overwritten

**Comment by Sukairo-02** [comment]
Oh, I see, that part is missing from non-complex keys, as well as key's name. expect a fix soon.
